
// Consultar os os usuários cadastrados
  GET http://localhost:3000/
###

// Consultar os usuário por id
GET http://localhost:3000/2


###

// Criar novo usuário
POST http://localhost:3000/
Content-Type: application/json

  {
    "id": 4,
    "nome": "Rafael",
    "idade": 25,
    "cidade": "Rio de Janeiro"
}

###

// Atualizar informações
PUT http://localhost:3000/2
Content-Type: application/json
  {
    "id": 2,
    "nome": "Rafael Pacheco",
    "idade": 25,
    "cidade": "Sorocaba"
  }







